@startuml
title Продление абонемента
(*) --> Начало
--> "Авторизация"
--> "Обращение по поводу абонемента?"
if "Обращение по поводу абонемента?" then
-left->[нет] "Оформление заморозки в системе"
--> "Приостановление действия абонемента"
else
-right->[да] "Определение условий продления"
--> "Оплата и активация нового периода"
--> "Уведомление клиента"
endif
@enduml