@startuml
title Покупка абонемента
(*) --> Начало
--> "Выбор абонемента"
if "Зарегистрированы?" then
-left->[нет] "Прохождение регистрации"
else
-right->[да] "Авторизация"
--> "Оплата услуги"
--> "Выдача абонемента"
endif
@enduml